exclude:
  - 'node_modules'
layouts_dir: 'node_modules/uptick-demo-site/dist'
package_name: Config Forms
package_github_url: https://github.com/uptick/config-forms
package_npm_url: https://www.npmjs.com/package/config-forms-react
